config/routes.rb
Nwokoroassociates::Application.routes.draw do

  resources :attorneys, only: [:index, :show]
  root :to => 'pages#home'

  match 'contact', to: 'contact#new', as: 'contact', via: :get
  match 'contact', to: 'contact#create', as: 'contact', via: :post


  match 'areas_of_practice', to: 'pages#areas_of_practice'
  match 'contact_us', to: 'pages#contact_us'
  match 'about_us', to: 'pages#about_us'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Blogit::Engine => '/news', as: 'news_blog'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
	blogs
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body

  def username
    self.email.split('@').first
  end
end

app/models/attorney.rb
class Attorney < ActiveRecord::Base
  TITLES = ['Principal', 'Senior Associate', 'Associate', 'Office Manager']

	attr_accessible :avatar, :first_name, :last_name, :profile, :title
	has_attached_file :avatar, :storage => :s3, :styles => { :medium => '300x300>', :thumb => '100x100>'}, :default_url => '/images/:style/missing.png'

  class << self
    def get_associates_order_by_title
      order("title LIKE 'Principal' DESC", "title LIKE 'Senior Associate' DESC")
    end

    def office_manager
      find_by_title(TITLES.last)
    end
  end

  def office_manager?
    true if self.title == 'Office Manager'
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def to_param
  	"#{id} #{full_name}".parameterize
  end
end

app/models/message.rb
class Message

	include ActiveModel::Validations
	include ActiveModel::Conversion
	extend ActiveModel::Naming

   validates :name, :subject, :body, presence: true
   validates :email, presence: true, format: { with: /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i, message: "email format name@example.com" }

   attr_accessor :name, :email, :subject, :body

   def initialize(attributes = {})
   	attributes.each do |name,value|
   		send("#{name}=", value)
   	end
   end

   def persisted?
   	false
   end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
  end

  def login_required
  end
end

app/controllers/attorneys_controller.rb
class AttorneysController < ApplicationController
  def index
  	@attorneys = Attorney.get_associates_order_by_title
  end

  def show
  	@attorney = Attorney.find(params[:id])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
  	@message = Message.new
  end

  def create
  	@message = Message.new(params[:message])
  	if @message.valid?
  		NotificationsMailer.new_message(@message).deliver
  		redirect_to(root_path, notice: "Message was successfully sent")
  	else
  		flash.now.alert = "Please complete all required form fields"
  		render :new
  	end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def areas_of_practice
  end

  def about_us
  end

  def contact_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "Nwokoro & Associates LLP, P.C Attorneys at Law"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

	def nav_link(link_text, link_path)
		class_name = current_page?(link_path) ? 'active' : ''
		content_tag(:li, class: class_name) do
			link_to link_text, link_path
		end		
	end

	def law_firm_name
		'Nwokoro & Scola'
	end
end

app/helpers/attorneys_helper.rb
module AttorneysHelper
  def get_office_manager
    Attorney.office_manager
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/blogit_posts/_form.html.erb
<%= semantic_form_for @blogit_post, :url => blogit.posts_url, :html => {:method => :post } do |f| %>
<%= f.inputs do %>
	<%= f.input :title %>
	<%= f.input :body%>
	<% end %>
 <%= f.actions %>
<% end %>

app/views/admin/posts/_form.html.erb
<%= semantic_form_for @post, :url => news_blog.posts_url, :html => {:method => :post } do |f| %>
<%= f.inputs do %>
	<%= f.input :title %>
	<%= f.input :body%>
	<% end %>
 <%= f.actions %>
<% end %>

app/views/attorneys/index.html.haml
- provide(:title, "Attorneys")
#main
  .main-container.holder
    .heading
      %center
        %h1 N&A ATTORNEYS
    / grid-cols
    .grid-cols
      / col50
      - @attorneys.each do |attorney|
        .col50
          .col-holder
            - unless attorney.office_manager?
              = image_tag(attorney.avatar.url(:thumb), class: "image alignleft")
              %h5= link_to "#{attorney.full_name}", attorney_path(attorney)
              - if attorney.profile.length > 300
                = truncate(attorney.profile, :length => 250)
                = link_to 'More', attorney_path(attorney)
              - else
                = attorney.profile

app/views/attorneys/show.html.haml
%h1= @attorney.full_name
%ul
  %li= @attorney.profile
  %li= image_tag @attorney.avatar.url(:medium)

= link_to 'Return to Attorneys Page', attorneys_path

app/views/blogit/comments/_admin_links.html.erb
<%= login_required(class: "actions") do %>
  <%= link_to(t(:delete, scope: 'blogit.comments'), [@post, comment], method: :delete, confirm: t(:are_you_sure_you_want_to_remove_this_comment, scope: 'blogit.comments')) %>
<% end %>

app/views/blogit/comments/_comment.html.erb
<%= content_tag(:article, id: "blog_comment_#{comment.id}", class: "blog_comment") do %>
  <%= content_tag(:div, class: "blog_comment_name", id: "blog_comment_#{comment.id}_name") do %>
    <%= comment.website? ? link_to(comment.name, comment.website) : comment.name %>
    <%= t('blogit.comments.wrote') %>
  <% end %>


  <%= content_tag(:div, class: "blog_comment_body",
      id: "blog_comment_#{comment.id}_body") do %>
      <%= format_content comment.body || "" %>
  <% end %>

  <%= blog_tag(:footer, type: "comment") do %>
    <%=t :posted_on, scope: 'blogit.comments'%> 
    <%= time_tag(comment.created_at, format: blogit_conf.datetime_format) %>
  <% end %>

  <%= render partial: "blogit/comments/admin_links", locals: {comment: comment} %>

<% end if comment.persisted? %>

app/views/blogit/comments/_form.html.erb
<%= form_for [post, comment], remote: true,
  html: {
    class: "new_blog_comment", id: "new_blog_comment" } do |f| -%>

  <p><%=t :leave_a_comment, scope: 'blogit.comments'%></p>

  <%= field class: "hidden" do %>
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
    Hide me using CSS
  <% end %>

  <%= field do %>
    <%= f.label :name, t(:name, scope: 'blogit.comments') %><br>
    <%= f.text_field :name %>
    <%= errors_on(comment, :name) %>
  <% end %>

  <%= field do %>
    <%= f.label :email, t(:email_never_displayed, scope: 'blogit.comments') %><br>
    <%= f.email_field :email %>
    <%= errors_on(comment, :email) %>
  <% end %>

  <%= field do %>
    <%= f.label :website, t(:your_website, scope: 'blogit.comments') %><br>
    <%= f.url_field :website %>
    <%= errors_on(comment, :website) %>
  <% end %>

  <%= field do %>
    <%= f.label :body, t(:your_comment, scope: 'blogit.comments') %><br>
    <%= f.text_area :body %><br>
    <%= errors_on(comment, :body) %>
  <% end %>

  <%= actions do %>
    <%= f.submit t(:add_comment, scope: 'blogit.comments'), :disable_with => t(:adding_comment, scope: 'blogit.comments') %>
  <% end %>
<% end -%>

app/views/blogit/comments/create.js.erb
var $form = $("form#new_blog_comment");
<% if @comment.save %>
  $("#comments").append("<%= escape_javascript(render(@comment)) %>");
  $form.get(0).reset();
<% else %>
  $form.html("<%= escape_javascript(render('form')) %>");
<% end %>

app/views/blogit/comments/destroy.js.erb
$("#comment_<%= @comment.id %>").remove();

app/views/blogit/posts/_active_record_comments.html.erb
<div id="comments">
  <%= render post.comments %>
</div>
<%= render partial: "blogit/comments/form", locals: { post: post, comment: comment } %>

app/views/blogit/posts/_blog_post_spacer.html.erb
<hr class="blog_post_spacer">

app/views/blogit/posts/_blogger_information.html.erb
<%= blog_tag :footer do %>
    <%=t :written_by, scope: 'blogit.posts', author: post.blogger_display_name %>
    <%= time_tag(post.created_at, pubdate: true, format: blogit_conf.datetime_format) %>
<% end %>

app/views/blogit/posts/_comments_count.html.erb
<%= content_tag(:div, class: "blog_post_comments_count", id: "blog_post_#{post.id}_comments_count") do %>
  <%= link_to(post_path(post, anchor: "comments")) do %>
    <%=t :comment, scope: 'blogit.posts', count: post.comments_count %>
  <% end %>
<% end %>

app/views/blogit/posts/_disqus_comments.html.erb
 <div id="disqus_thread"></div>
 <script type="text/javascript">
   /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
   var disqus_shortname = '<%= Blogit.configuration.disqus_shortname %>'; // required: replace example with your forum shortname

   /* * * DON'T EDIT BELOW THIS LINE * * */
   (function() {
     var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
     dsq.src = '<%= request.protocol %>' + disqus_shortname + '.disqus.com/embed.js?<%= request.protocol_name %>';
     (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
   })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/blogit/posts/_empty.html.erb
<div class="blogit_empty_message">
  <%=t :there_are_no_posts_about, scope: 'blogit.posts', tag: params[:tag] %>
</div>

app/views/blogit/posts/_error_messages.html.erb
  <% if object.errors.any? %>
    <div id="error_explanation">
      <h2><%=t :prohibited_this_post_from_being_saved, scope: 'blogit.posts', count: @post.errors.count%></h2>

      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/blogit/posts/_form.html.erb
  <%= render 'error_messages', object: f.object %>
    <%= field do %>
      <div id="title"><%= f.text_field :title, placeholder: t(:give_your_post_a_title, scope: 'blogit.posts') %></div>
    <% end %>

    <%= field do %>
      <%= f.text_area :body, placeholder: t(:write_something_here, scope: 'blogit.posts') %>
    <% end %>

app/views/blogit/posts/_pagination.html.erb
<%= paginate(@posts) %>

app/views/blogit/posts/_post_links.html.erb
<%= login_required do  %>
  <%= actions do %>
    <%= link_to(t(:edit, scope: 'blogit.posts'), edit_post_path(post)) %> | <%= link_to(t(:delete, scope: 'blogit.posts'), post, method: :delete, confirm: t(:are_you_sure_you_want_to_remove_this_post, scope: 'blogit.posts')) %>
  <% end %>
<% end unless blogit_conf.author_edits_only and not this_blogger?(post) %>

app/views/blogit/posts/_share_bar.html.erb
<div id="blog_share_bar">

  <div id="google-plus" class="social_button">
    <!-- GOOGLE +1 -->
    <g:plusone size="medium"></g:plusone>
    <script type="text/javascript">
      window.___gcfg = {lang: '<%= I18n.default_locale %>'};

      (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
    </script>
    <!-- /GOOGLE +1 -->
  </div>

  <div id="twitter" class="social_button">
    <!-- TWITTER -->
    <a href="https://twitter.com/share" class="twitter-share-button"
        data-lang="<%= I18n.default_locale %>"
        data-url="http://<%= request.host_with_port %><%= request.path.gsub("//","/") %>"
        data-via="<%= Blogit.configuration.twitter_username %>"
        data-text="<%= post.title%>"
        data-count="horizontal">Tweet</a>

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <!-- /TWITTER -->
  </div>

  <div id="facebook" class="social_button">
    <!-- FACEBOOK LIKE -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/<%= t "blogit.share_bar.facebook" %>/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <div class="fb-like" data-send="false"  data-layout="button_count" data-width="90" data-show-faces="false"></div>
    <!-- /FACEBOOK LIKE -->
  </div>

</div>

app/views/blogit/posts/edit.html.erb
<%= form_for(@post, html: {class: "new_blog_post", id: "new_blog_post"}) do |f| %>
<h2><%=t :edit_blog_post, scope: 'blogit.posts', id: @post.id %></h2>

<fieldset>
  <legend>Edit Blog Post</legend>
    <%= render 'form', f: f %>
  </fieldset>
  <fieldset>

    <p class="blog_post_tip">
      <%t :tip_you_can_style_your_post_using, scope: 'blogit.posts', parser: blogit_conf.default_parser %>
    </p>
    <%= actions do %>
    <%= f.submit %> <%=t :or, scope: 'blogit.posts'%>
    <%= link_to(t(:cancel, scope: 'blogit.posts'), @post.new_record? ? blog_root_path : post_path(@post)) %>
  <% end %>
  </fieldset>
  <% end %>

app/views/blogit/posts/new.html.erb
<%= form_for(@post, html: {class: "new_blog_post", id: "new_blog_post"}) do |f| %>
<h2><%t :write_a_new_blog_post, scope: 'blogit.posts'%></h2>
<fieldset>
  <legend>Write New Blog Post</legend>
    <%= render 'form', f: f %>
  </fieldset>
<fieldset>

    <p class="blog_post_tip">
      <%t :tip_you_can_style_your_post_using, scope: 'blogit.posts', parser: blogit_conf.default_parser %>
    </p>
    <%= actions do %>
    <%= f.submit "Add New Post" %> <%=t :or, scope: 'blogit.posts'%>
    <%= link_to(t(:cancel, scope: 'blogit.posts'), @post.new_record? ? blog_root_path : post_path(@post)) %>
  <% end %>
  </fieldset>
  <% end %>

app/views/blogit/posts/show.html.erb
<%= render @post %>
<%= share_bar_for @post %>
<%= render "blogit/posts/post_footer", post: @post %>
<%= comments_for @post %>

app/views/contact/new.html.haml
.main-container.holder
  %center
    %h1 Contact Us
  .grid-cols
    .col50
      .col-holder
        %center
          %h1 Phone: (212) 785-1060
    .col50
      .col-holder
        %center
          %h1 Email: Direct@Nwokoroassociates.com
  .divider
  / grid-cols
  .grid-cols
    / col33
    .col33
      .col-holder
        %h3 MAIN OFFICE
        %dl
          82 Wall Street, Suite 610
          %br
            New York, New York 10005
            %br
              Telephone: (212) 785-1060
        .divider
        / contact
        %h4 BROOKLYN OFFICE
        %dl
          801 Franklin Avenue
          %br
            Brooklyn, New York 11238
            %br
        .divider
        / contact
        %h4 NEW JERSEY OFFICE
        %dl
          1 Eves Drive, Suite 111
          %br
            Marlton, New Jersey 08053
            %br
    / col67
    .col67
      .col-holder
        .flash_message
          = flash[:alert]
        / post-box
        <article class="contact-post-box">
        = form_for @message, :url => contact_path, :html => { class: "comment-form", id: "cont_form"} do |f|
          %fieldset
          .meta
            %h3 Contact Us
          .row
            = f.label :name, "Your Name"
            %span.text
              = f.text_field :name, placeholder: "required"
          .row
            = f.label :email, "Email"
            %span.text
              = f.text_field :email, placeholder: "required"
          .row
            = f.label :subject, "Subject"
            %span.text
              = f.text_field :subject
          .row
            = f.label :body, "Message"
            %span.textarea
              = f.text_area :body, placeholder: "required", cols: 30, rows: 10, class: "w_focus validate[required]", id: "message"
          .row
            %span.submit
              Send Email
              = f.submit "Send Message"

app/views/layouts/_footer.html.erb
						<div class="grid-cols">
							  <div class="col25">
									<div class="col-holder">								
										&nbsp;
                                      
										<ul class="links">
                                            <li><%= link_to 'About Us', about_us_path %></li>
											<li><%= link_to 'Contact Us', contact_us_path %></li>
											<li><%= link_to 'Areas of Practice', areas_of_practice_path %></li>
										</ul>
									</div>
								</div>
                            
								<div class="col50">
									<div class="col-holder">
										   &nbsp;
										<dl>
											<dt>Telephone:</dt>
											<dd>(212) 785-1060</dd>
											<dt>E-mail:</dt>
											<dd><%= mail_to 'direct@nwokoroassociates.com', 'Direct@Nwokoroassociates.com' %></dd>
										<address>
                                        <dt>Address:</dt>
											      <b>82 Wall Street, Suite 610, New York, New York 10005</b>
										</address>
                                        </dl>
									</div>
                                  <div class="by">
                                    &copy; Copyright <%= Date.today.year %>. <a href="#">Nwokoro & Associates, P.C.</a>. All right reserved.
                                  </div>
								</div>

                        </div>

app/views/layouts/_header.html.haml
#main
  / FlexSlider with Thumbs
  - if current_page?('/')
    \&nbsp;
    %center
      %h1
        #{law_firm_name}, P.C.
        Attorneys At Law
        .notice_success
          = flash[:notice]
      \&nbsp;
  .gallery
    .flexslider-container
      #slider.flexslider.holder
        %ul.slides
          %li
            = image_tag("wallstreetsign1.png")

app/views/layouts/_nav.html.erb
			
				<ul id="nav">
							<%= nav_link('Home', root_path) %>						
							<%= nav_link('About Us', about_us_path) %>
							<%= nav_link('Areas of Practice', areas_of_practice_path)%>
							<%= nav_link('Attorneys', attorneys_path) %>
							<%= nav_link('Contact Us', contact_path) %>						
							<%= nav_link('Blog', "#{news_blog.posts_path}")%>
							<% if current_admin_user %>
								<%= nav_link('Sign out', "/admin/logout") %>
								<%= nav_link('Admin', "/admin") %>
								<% end %>
									
						</ul>
						<select class="mobile-menu">
						<option value="" selected="selected">Select</option>
							<option value= "/" >Home</option>													
							<option value= "/about_us"> About Us</option>
							<option value= "/areas_of_practice"> Areas of Practice</option>
							<option value= "/attorneys"> Attorneys</option>
							<option value="/contact" > Contact Us</option>
							<option value= "/blog" > Blog		</option>
						</select>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application.css", :media => "all" %>

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body class="inner">
<div id="wrapper">
	<div class="w2">
		<header id="header">
			<div class="section">
				<h1 class="logo"><%= link_to "N&A", '/' %></h1>
				<div class="contact-box">
							<strong class="phone">(212) 785-1060</strong>	
						</div>
			</div>
			<nav class="nav-box">
			<%= render 'layouts/nav' %>
			</nav>
			<%= render 'layouts/header' %>
		</header>							
</div>
	</div>
</div>

<%= yield %>
<div class="divider">							
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about_us.html.haml
/ boxes
.main-container.holder
  %center
    %h1 MISSION STATEMENT
  \&nbsp;
  %center
    %h2 A BETTER WAY TO DEFEND
  \&nbsp;
  %p
    N & A is an emergent law firm that is bringing a better way to defend general liability actions. Our focus is twofold:
    First; an effective and competent defense of the case at hand.
    Secondly; a commitment to minimizing legal costs.
    To that effect, we have implemented an innovative billing system that is a hybrid of task based and hourly billing systems. This new age system operates to provide a stellar defense while ensuring that the fees charged are commensurate with the profile of the case.
  %br/
  %p Unlike the larger firms whose practices and procedures have devolved to become a set of boiler plate responses that often do not account for the particular requirements of each individual case, we bring a personalized approach that is tailored to the specific demands of each individual case.  Of course, we also implement the client's guidelines regarding billing and reporting.
  %br/
  %p
    On reporting, we are committed to communicating concisely and in a timely manner with our clients. The object is to report often but in a concise manner and keep the client apprised of significant events and facts without repetition or replication. A compact presentation of significant information is to be preferred to a lengthy recital of the less impactful aspects of the case.
  %br/

app/views/pages/areas_of_practice.html.haml
.main-container.holder
  %center
    %h1 AREAS OF PRACTICE
  .practice-table
    .col.col3
      .title.black
        %h3 General Liability
      .holder
        %div
        \&nbsp;
        %h4 We handle general liability cases including all types of premises liability and general negligence actions, commercial liability cases, and homeowner claims. We also handle subrogation actions and indemnity actions when necessary.
    .col.col3
      .title.black
        %h3 Transportation Liability
      .holder
        %div
        \&nbsp;
        %h4 We provide a defense against automobile liability cases including third party auto liability actions and no fault matters.
    .col.col3
      .title.black
        %h3 Municipal Liability
      .holder
        %div
        \&nbsp;
        %h4 We handle the defense of all negligence claims against municipalities and municipal entities including premises liability and highway and other design defect liability.
    \&nbsp;
    ________________________________________________________________________________________________________________________________
  .practice-table
    .col.col3
      .title.black
        %h3 Product Liability
      .holder
        %div
        \&nbsp;
        %h4 Defending manufacturers against suits relating to claims of defectively designed or manufactured products.
    .col.col3
      .title.black
        %h3 Insurance Coverage Litigation
      .holder
        %div
        \&nbsp;
        %h4 We bring declaratory judgment actions and provide advise on insurance coverage, insurance coverage opinions, disclaimer letters.
    \&nbsp;
    .col.col3
      .title.black
        %h3 Appeals
      .holder
        %div
        \&nbsp;
        %h4 We offer our clients a very respectable appellate representation on all issues arising out of the cases that we handle, whether as an appellant or as the respondent. We provide clients with an even-handed opinion on the merits of each appeal, followed by competent representation when required.
    \&nbsp;
    ________________________________________________________________________________________________________________________________

  .practice-table
    .col.col3
      .title.black
        %h3 Toxic Tort Liability
      .holder
        %div
        \&nbsp;
        %h4 We offer a stellar defense against claims of injuries arising from lead paint, mold or other toxic environmental elements.
    .col.col3
      .title.black
        %h3 Civil Rights & Employment Discrimination Defense
      .holder
        %div
        \&nbsp;
        %h4 We represent municipalities, public corporations and private entities in the defense of claims of civil rights violations and employment discrimination.
    .col.col3
      .title.black
        %h3 Construction Liability
      .holder
        %div
        \&nbsp;
        %h4 We handle cases brought against owners, contractors and sub-contractors under New York's Labor Law including enforcement of indemnity claims between parties and declaratory judgment actions against those parties in breach of their obligations to our clients.
    \&nbsp;

app/views/pages/contact_us.html.haml
.main-container.holder
  %center
    %h1 Contact Us
  .grid-cols
    .col50
      .col-holder
        %center
          %h1 Phone: (212) 785-1060
    .col50
      .col-holder
        %center
          %h1 Email: Direct@Nwokoroassociates.com
  .divider
  / grid-cols
  .grid-cols
    / col33
    .col33
      .col-holder
        %h3 MAIN OFFICE
        %dl
          82 Wall Street, Suite 610
          %br
            New York, New York 10005
            %br
              Telephone: (212) 785-1060
        .divider
        / contact
        %h4 BROOKLYN OFFICE
        %dl
          801 Franklin Avenue
          %br
            Brooklyn, New York 11238
            %br
        .divider
        / contact
        %h4 NEW JERSEY OFFICE
        %dl
          1 Eves Drive, Suite 111
          %br
            Marlton, New Jersey 08053
            %br
    / col67
    .col67
      .col-holder
        / post-box

        <article class="contact-post-box"">
        <article class="post-box">

        / comment-form
        %form#cont_form.comment-form{:action => "#", :method => "post"}/
        %fieldset
          .meta
            %h3 Contact Us
          .row
            %label{:for => "username"} Your Name  (*)
            %span.text
              %input#username.text{:class => "validate[required]", :name => "username", :type => "text", :value => ""}/
          .row
            %label{:for => "email"} Your Email  (*)
            %span.text
              %input#email.text{:class => "validate[required,custom[email]]", :name => "email", :type => "text", :value => ""}/
          .row
            %label{:for => "subject"} Your Subject
            %span.text
              %input#subject.text{:name => "subject", :type => "text", :value => ""}/
          .row
            %label{:for => "message"} Your Message  (*)
            %span.textarea
              %textarea#message.w_focus{:class => "validate[required]", :cols => "30", :name => "message", :rows => "10"}
          .row
            %span.submit
              Send Email
              %input{:type => "submit", :value => "Send Email"}/

app/views/pages/home.html.haml
- provide(:title, 'Home')
/ main
.main-container.holder
  %center
    %h2 A BETTER WAY TO DEFEND
    \&nbsp;
    %h3 "#{law_firm_name}" is a general liability defense law firm. We offer specialized legal services to insurance carriers, third party claim administrators and self-insured entities or individuals. We combine core competence, varied experience and industry knowhow with a new age ethical billing concept and individual handling of client matters tailored to the unique needs of each client.
    %br/
  .info
    - unless get_office_manager.nil?
      = image_tag 'nwokoro-banner.png', class: "image alignleft"


  